package com.rockeycui.learn.wechat.mapper;

import com.rockeycui.learn.wechat.domain.WxAccessToken;
import com.rockeycui.learn.wechat.domain.WxAccessTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated
     */
    int countByExample(WxAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated
     */
    int deleteByExample(WxAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated
     */
    int insert(WxAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated
     */
    int insertSelective(WxAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated
     */
    List<WxAccessToken> selectByExample(WxAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WxAccessToken record, @Param("example") WxAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WxAccessToken record, @Param("example") WxAccessTokenExample example);
}