server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RockeyCui/config/
          searchPaths: backend,usercenter
          username:
          password:
        encrypt:
          enabled: false